# Generated by Django 4.2.6 on 2023-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
