# Generated by Django 4.2.6 on 2023-11-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_like_answers_remove_like_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
