# Generated by Django 4.2.6 on 2023-11-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_like_answers_remove_like_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
